spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  # druid
  datasource:
     url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=GMT%2B8&amp
     username: root
     password: 123
     type: com.alibaba.druid.pool.DruidDataSource
     filters: stat
     maxActive: 1000
     initialSize: 100
     maxWait: 60000
     minIdle: 500
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20
     driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    add-mappings: true
    cache-period: 3600
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
  rabbitmq:
     host: 192.168.152.132
     port: 5672
     username: guest
     password: guest
     virtual-host: /
     listener:
         simple:
            concurrency: 10
            max-concurrency: 10
            prefetch: 1
            auto-startup: true
            default-requeue-rejected: true
     template:
         retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            max-interval: 10000
            multiplier: 1.0


mybatis:
  type-aliases-package: com.imooc.miaosha.domain
  configuration:
     map-underscore-to-camel-case: true
     default-fetch-size: 100
     default-statement-timeout: 3000
  mapperLocations: classpath:com/imooc/miaosha/dao/*.xml
#redis
redis:
   host: 192.168.152.132
   port: 6379
   timeout: 3
   poolMaxTotal: 5000
   poolMaxIdle: 500
   poolMaxWait: 500


#logging:
#  level:
#    com:
#      imooc:
#        miaosha:
#          dao: debug
